# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# NOTE: pnpm caching support requires pnpm version >= 6.10.0

name: Build and Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run eslint
        run: pnpm lint

  build-and-publish:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            dist: win
          - os: ubuntu-latest
            name: Linux
            dist: linux
          - os: macos-latest
            name: macOS
            dist: mac
    runs-on: ${{ matrix.os }}

    name: Build ${{ matrix.name }} Distribution
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build dist with electron-builder
        run: pnpm dist:${{ matrix.dist }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4.0.0
        with:
          name: prime-hint-tracker-${{ matrix.dist }}
          if-no-files-found: error
          path: |
            dist/prime-hint-tracker*.msi
            dist/prime-hint-tracker*.exe
            dist/prime-hint-tracker*.dmg
            dist/prime-hint-tracker*.AppImage
